vpc_ip: "{{ host_vpc_ips[inventory_hostname] }}"
docker_insecure_registries: ["docker-registry.internal"]
local_host_aliases:
  - docker-registry.internal
nomad_network: '172.16.0.0/16'
nomad_client_region: cloud
nomad_server_join:
  - sgp-nomad-core1
  - sgp-nomad-core2
  - sgp-hostedbeans-1
nomad_client_join:
  - sgp-nomad-core1
  - sgp-nomad-core2
  - sgp-hostedbeans-1
