---
nomad_advertise_addr: ''
nomad_network: ''
nomad_client_region: 'global'
nomad_client_dc: 'dc1'
nomad_cni_plugin_version: 'v1.6.2'
nomad_server_join: []
nomad_client_join: []
nomad_client_meta: {}
nomad_client_config: ""
