---
- name: install apt packages
  apt:
    name: '{{item}}'
    update_cache: true
  loop:
    - cron
    - htop
    - lsof
    - sysstat # provides iostat

- name: uninstall snap
  apt:
    name: '{{item}}'
    state: absent
    purge: yes
  loop:
    - snap
    - snapd
