---
- name: create nomad jobs directory
  file:
    path: /etc/nomad.d/jobs
    state: directory
    mode: '0755'
  when: nomad_run_jobs | length > 0

- name: flush handlers before running jobs
  meta: flush_handlers
  when: nomad_run_jobs | length > 0

- name: initialize expanded job list
  set_fact:
    nomad_run_jobs_expanded: []

- name: expand nomad job paths (support glob patterns)
  set_fact:
    nomad_run_jobs_expanded: "{{ nomad_run_jobs_expanded + (lookup('fileglob', item, wantlist=True) if '*' in item else [item]) }}"
  loop: '{{ nomad_run_jobs }}'

- name: copy nomad job files
  copy:
    src: '{{ item }}'
    dest: '/etc/nomad.d/jobs/{{ item | basename }}'
    mode: '0644'
  loop: '{{ nomad_run_jobs_expanded }}'
  register: nomad_job_files

- name: run nomad jobs
  command: nomad run '{{ item.dest }}'
  loop: '{{ nomad_job_files.results }}'
  when: item.changed
