---
- name: download hashicorp apt key
  get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
    mode: '0644'

- name: add apt repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"
    filename: hashicorp

- name: install apt packages
  apt:
    name: nomad
    update_cache: true

- name: create cni bin directory
  file:
    path: /opt/cni/bin
    state: directory
    mode: '0755'

- name: install cni plugins
  unarchive:
    src: "https://github.com/containernetworking/plugins/releases/download/{{ nomad_cni_plugin_version }}/cni-plugins-linux-{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else 'amd64' }}-{{ nomad_cni_plugin_version }}.tgz"
    dest: /opt/cni/bin
    remote_src: true
    mode: '0755'
    creates: /opt/cni/bin/bridge

- name: configure nomad docker plugin
  copy:
    dest: /etc/nomad.d/plugin-docker.hcl
    content: |
      plugin "docker" {
        config {
          volumes {
            enabled = true
          }
        }
      }
    mode: '0644'
  notify:
    - restart nomad

- name: setup nomad agent
  lineinfile:
    path: /etc/nomad.d/nomad.hcl
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^region\s=', line: 'region = "{{ nomad_agent_region }}"' }
    - { regexp: '^datacenter\s=', line: 'datacenter = "{{ nomad_agent_datacenter }}"' }
  notify:
    - restart nomad

- name: enable nomad service
  service:
    name: nomad
    enabled: true
  notify:
    - restart nomad
