global:
  scrape_interval: 5m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'node'
    scheme: https
    basic_auth:
      username: admin
      password: '{{ prometheus_basic_auth }}'
    # proxy_url: 'http://10.0.0.1:8118'
    static_configs:
      - targets: ['metrics.hostedbeans.io']
        labels:
          product: hostedbeans
          instance: hostedbeans-1
          __metrics_path__: /nodes/hostedbeans-1/metrics

  - job_name: 'hostedbeans'
    scheme: https
    basic_auth:
      username: admin
      password: '{{ prometheus_basic_auth }}'
    # proxy_url: 'http://10.0.0.1:8118'
    static_configs:
      - targets: ['metrics.hostedbeans.io']
        labels:
          product: hostedbeans
          instance: hostedbeans-1
          __metrics_path__: /hostedbeans/metrics
